### ISSUE TITLE
Low Quality/Over Zoomed/Cropped Art

### ISSUE THREAD

**Issue by digitalbarrito** [Fxy6969/Stremio-Glass-Theme#1]
As the title says, the art with this theme isn't very good,

I assume it's just resizing/cropping the existing art and I'm not sure if there's anything you can do to solve that, so my potential suggestion is to reconsider the actual shape and size of the items on screen so the artwork doesn't get pixelated and over-cropped.

**Comment by Fxy6969** [comment]
This has been fixed.
